"""13:04 30.11.2025

Revision ID: 05eee169c8d0
Revises: 0cbd2fb19970
Create Date: 2025-11-30 13:07:14.358099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05eee169c8d0'
down_revision: Union[str, Sequence[str], None] = '0cbd2fb19970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('theme_file',
    sa.Column('theme_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.theme_id'], ),
    sa.PrimaryKeyConstraint('theme_id', 'file_id')
    )
    op.add_column('exam', sa.Column('rate', sa.String(), nullable=True))
    op.add_column('exam_theme', sa.Column('exam_theme_order', sa.Integer(), nullable=False))
    op.add_column('theme', sa.Column('theme_order', sa.Integer(), nullable=False))
    op.drop_column('theme', 'file_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('file_list', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('theme', 'theme_order')
    op.drop_column('exam_theme', 'exam_theme_order')
    op.drop_column('exam', 'rate')
    op.drop_table('theme_file')
    op.drop_table('file')
    # ### end Alembic commands ###
