"""27.10.2025 20:01

Revision ID: 069ffaf3033d
Revises: 
Create Date: 2025-10-27 20:06:09.045398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069ffaf3033d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_exam', sa.DateTime(), nullable=False),
    sa.Column('end_exam', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('exam_question',
    sa.Column('exam_question_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.PrimaryKeyConstraint('exam_question_id')
    )
    op.create_table('answer',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('exam_question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_question_id'], ['exam_question.exam_question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('exam_question')
    op.drop_table('question')
    op.drop_table('exam')
    # ### end Alembic commands ###
