"""17.11.2025 20:00

Revision ID: 0cbd2fb19970
Revises: 7391fefd7ff0
Create Date: 2025-11-17 20:01:53.997483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbd2fb19970'
down_revision: Union[str, Sequence[str], None] = '7391fefd7ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('type', sa.String(), nullable=False))
    op.add_column('question', sa.Column('answer_text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer_text')
    op.drop_column('exam', 'type')
    # ### end Alembic commands ###
