"""14:52 04.11.2025

Revision ID: 1cf62b812fd1
Revises: 069ffaf3033d
Create Date: 2025-11-04 14:53:34.281658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf62b812fd1'
down_revision: Union[str, Sequence[str], None] = '069ffaf3033d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('theme_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('theme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme')
    # ### end Alembic commands ###
