"""11:44 07.11.2025

Revision ID: 5b648bf33468
Revises: 1cf62b812fd1
Create Date: 2025-11-07 11:45:34.335966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b648bf33468'
down_revision: Union[str, Sequence[str], None] = '1cf62b812fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('file_list', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme', 'file_list')
    # ### end Alembic commands ###
