"""13:04 08.11.2025

Revision ID: 7391fefd7ff0
Revises: d53efcda5bb4
Create Date: 2025-11-08 13:09:27.678921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7391fefd7ff0'
down_revision: Union[str, Sequence[str], None] = 'd53efcda5bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_theme',
    sa.Column('exam_theme_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('exam_theme_id')
    )
    op.add_column('exam', sa.Column('exam_theme_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'exam', 'exam_theme', ['exam_theme_id'], ['exam_theme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'exam_theme_id')
    op.drop_table('exam_theme')
    # ### end Alembic commands ###
