"""11:55 07.11.2025

Revision ID: d1a3cc0f26d6
Revises: 5b648bf33468
Create Date: 2025-11-07 11:58:18.322032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a3cc0f26d6'
down_revision: Union[str, Sequence[str], None] = '5b648bf33468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme', 'document_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('document_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
