"""12:17 07.11.2025

Revision ID: d53efcda5bb4
Revises: d1a3cc0f26d6
Create Date: 2025-11-07 12:17:15.987550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53efcda5bb4'
down_revision: Union[str, Sequence[str], None] = 'd1a3cc0f26d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('theme_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'question', 'theme', ['theme_id'], ['theme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'theme_id')
    # ### end Alembic commands ###
